version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db

  swagger-merger:
    build:
      context: .
      dockerfile: ./swagger/swagger-merger/Dockerfile
    command: >
      watch 'swagger-merger -i ./swagger/src/index.yml -o ./swagger/dist/swagger.yml' /swagger/src/
    volumes:
      - ./swagger:/swagger

  redoc:
    image: redocly/redoc
    ports:
      - 8081:80
    volumes:
      - ./swagger/dist:/usr/share/nginx/html/swagger
    environment:
      SPEC_URL: swagger/swagger.yml

volumes:
  bundle_path:
